//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModManager.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModManager.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions_Activate.
        /// </summary>
        public static string Actions_Activate {
            get {
                return ResourceManager.GetString("Actions_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions_Indicator.
        /// </summary>
        public static string Actions_Indicator {
            get {
                return ResourceManager.GetString("Actions_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column_Actions.
        /// </summary>
        public static string Column_Actions {
            get {
                return ResourceManager.GetString("Column_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column_Author.
        /// </summary>
        public static string Column_Author {
            get {
                return ResourceManager.GetString("Column_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column_Indicators.
        /// </summary>
        public static string Column_Indicators {
            get {
                return ResourceManager.GetString("Column_Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column_Mods.
        /// </summary>
        public static string Column_Mods {
            get {
                return ResourceManager.GetString("Column_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Confirm.
        /// </summary>
        public static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Deletion_Message.
        /// </summary>
        public static string Dialog_Deletion_Message {
            get {
                return ResourceManager.GetString("Dialog_Deletion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Deletion_Title.
        /// </summary>
        public static string Dialog_Deletion_Title {
            get {
                return ResourceManager.GetString("Dialog_Deletion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Discard.
        /// </summary>
        public static string Dialog_Discard {
            get {
                return ResourceManager.GetString("Dialog_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Rename_Message.
        /// </summary>
        public static string Dialog_Rename_Message {
            get {
                return ResourceManager.GetString("Dialog_Rename_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Rename_Title.
        /// </summary>
        public static string Dialog_Rename_Title {
            get {
                return ResourceManager.GetString("Dialog_Rename_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog_Save.
        /// </summary>
        public static string Dialog_Save {
            get {
                return ResourceManager.GetString("Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit_Header.
        /// </summary>
        public static string Edit_Header {
            get {
                return ResourceManager.GetString("Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status_Header.
        /// </summary>
        public static string Status_Header {
            get {
                return ResourceManager.GetString("Status_Header", resourceCulture);
            }
        }
    }
}
